# This file was generated by GoReleaser. DO NOT EDIT.
cask "astrogui" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a00c1698a8b4a00920ca7102e3c44f4a55d7ac1c6ae48b8a4057588dbd24a50e"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "351d1e2a84c6153b50f0a607bcc1f10483a6b576406dba1bbe91321c4cf27a37"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2dcdd1f568e6d9cc5a5987a6312846086207da8f9d441ad7f0ce1cdd84c63167"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c5242b1a0d744ad2c99d4ebc31397be55edada53e40a23725a1d7ea9e064d1d"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "astrogui"
  desc "Local cockpit for an Astro blog: draft kanban board and markdown editor"
  homepage "https://github.com/amagyar/astrogui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astrogui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astrogui"]
    end
  end

  # No zap stanza required
end
