# This file was generated by GoReleaser. DO NOT EDIT.
cask "astrogui" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "46d13857c11023d185c8d86c1dccf83904a0d4371d187aaed93f3915f446d5f8"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a801323ebf50522fd881ceef8f0c898b9ed3b17a4e2f7b8734120cac4a06c60e"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1bb51b3fd53be1523b4b51e78a2d727cd0e394171a22bca89f46d57c01f24f05"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acd9323470dbb4cec2e9f301cf353a1aa2d605c73a342d3b866c4ae3ad71244c"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "astrogui"
  desc "Local cockpit for an Astro blog: draft kanban board and markdown editor"
  homepage "https://github.com/amagyar/astrogui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astrogui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astrogui"]
    end
  end

  # No zap stanza required
end
