# This file was generated by GoReleaser. DO NOT EDIT.
cask "astrogui" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "35ee9a977acf397ad637812c247f1a83f3150bfec7f5709ada8453d4f83f561d"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd3335cc1118dea18454c8d8fc53faff84ce5bb22ccf9ada4b9d59d91ccf71b1"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32aa58cd720f786d4e7269814df5404a5b407c048436b22f825eb360f0c2b049"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31aec6fbf0ce96d9752508cb6bbefcb88881a6f4e8c8d64e46b5d926618cc05f"
      url "https://github.com/amagyar/astrogui/releases/download/v#{version}/astrogui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "astrogui"
  desc "Local cockpit for an Astro blog: draft kanban board and markdown editor"
  homepage "https://github.com/amagyar/astrogui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astrogui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astrogui"]
    end
  end

  # No zap stanza required
end
