# This file was generated by GoReleaser. DO NOT EDIT.
cask "dockupdate" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "7592295e55e7d316485f2dbc957f439f4fcb8a2101217da2b29f5a11ec248d39"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f14b6468a805f3b73f5e7dd756453a67b85b246f31244b507189098386e581b3"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d002ce4fe5a1cc0700e86ea804656899671a63b15273ad1d349ea5a611e62288"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c1ef3c8bfd49b08165a2f28e2a6385aa5204fecd098424ad3e9abcca8bec832"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dockupdate"
  desc "Terminal UI to manage Docker/Podman containers and their updates"
  homepage "https://github.com/amagyar/dockupdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dockupdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dockupdate"]
    end
  end

  # No zap stanza required
end
