# This file was generated by GoReleaser. DO NOT EDIT.
cask "dockupdate" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "1dad47b8f388ef26a163e74ede7b66abb81c2c23017fa8b5e989b88910cba85f"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
    on_arm do
      sha256 "a8089ef3f32b06cc0f0dbb00167431cd36317fe7d373e8eeb91e83528f98f6d3"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
  end

  on_linux do
    on_intel do
      sha256 "2dc79dbd87907de9ca612668ba1b6c8815af9e248d161e5c972b6e8a8917ca78"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_amd64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
    on_arm do
      sha256 "397acd93ddda0690af118e5348f012535f8fd4490139bfba57038e687e23d30c"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_arm64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
  end

  name "dockupdate"
  desc "Terminal UI to manage Docker/Podman containers and their updates"
  homepage "https://github.com/amagyar/dockupdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dockupdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dockupdate"]
    end
  end

  # No zap stanza required

end
