# This file was generated by GoReleaser. DO NOT EDIT.
cask "dockupdate" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "576190d1d2568f5c544123b3689365c7196453c2356ba451724776d9c1e364d9"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
    on_arm do
      sha256 "d1c391c86d457d77883e481dc2c95229ec84138d495bb66da63ebd866c336b30"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
  end

  on_linux do
    on_intel do
      sha256 "07fabd02fa8049c56c1134c5ef3a97642ac58a59d1a00ad96e5d030f0d23f016"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_amd64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
    on_arm do
      sha256 "c17937132137da07e10395c3565929360bd4321d517100e271a6806c62f33191"
      url "https://github.com/amagyar/dockupdate/releases/download/v#{version}/dockupdate_#{version}_linux_arm64.tar.gz",
        verified: "github.com/amagyar/dockupdate"
    end
  end

  name "dockupdate"
  desc "Terminal UI to manage Docker/Podman containers and their updates"
  homepage "https://github.com/amagyar/dockupdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dockupdate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dockupdate"]
    end
  end

  # No zap stanza required

end
