# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockupdate < Formula
  desc "Terminal UI to manage Docker/Podman containers and their updates"
  homepage "https://github.com/amagyar/dockupdate"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amagyar/dockupdate/releases/download/v0.1.0/dockupdate_0.1.0_darwin_amd64.tar.gz"
      sha256 "fe53bce8feb1b044e47e29f7dbc1f14b84bd066ba0ea91cf70a77b8090c226bc"

      define_method(:install) do
        bin.install "dockupdate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amagyar/dockupdate/releases/download/v0.1.0/dockupdate_0.1.0_darwin_arm64.tar.gz"
      sha256 "a949ccc1b132c05184d8c7c514c2e622b01ec379a365bef12e5bf770f3128c28"

      define_method(:install) do
        bin.install "dockupdate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amagyar/dockupdate/releases/download/v0.1.0/dockupdate_0.1.0_linux_amd64.tar.gz"
      sha256 "bc289680e15a8590a80be58bbf5b0eeb27f152248feb725fae4b11e19c0604db"
      define_method(:install) do
        bin.install "dockupdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amagyar/dockupdate/releases/download/v0.1.0/dockupdate_0.1.0_linux_arm64.tar.gz"
      sha256 "69c3c01c838868f0d734f81d240324b106a690a07827931cb66a7da6e19947eb"
      define_method(:install) do
        bin.install "dockupdate"
      end
    end
  end

  test do
    system "#{bin}/dockupdate --version"
  end
end
